---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  namespace: sample
  labels:
    app: sample
  annotations:
    fluxcd.io/automated: 'true'
    fluxcd.io/tag.app: semver:~1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: sample
        image: norbin/go-gitops:1.0.0
        ports:
        - containerPort: 80
